[package]
name = "uma_quiz"
version = "0.3.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
proconio = "0.5.0"
color-eyre = "0.6.5"
colored = "3"
chrono = { version = "0.4.41", features = ["serde"] }
